"""change tags table

Revision ID: 25a6378f630b
Revises: 8f4267359391
Create Date: 2022-01-02 16:01:30.780909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25a6378f630b'
down_revision = '8f4267359391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('tag_ibfk_1', 'tag', type_='foreignkey')
    op.drop_column('tag', 'tag')
    op.drop_column('tag', 'img_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('img_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tag', sa.Column('tag', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_foreign_key('tag_ibfk_1', 'tag', 'image', ['img_id'], ['id'])
    op.drop_column('tag', 'id')
    # ### end Alembic commands ###
