"""add tag and position

Revision ID: 8f4267359391
Revises: b16246790954
Create Date: 2021-12-31 16:47:04.452777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4267359391'
down_revision = 'b16246790954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.String(length=20), nullable=True),
    sa.Column('x1', sa.String(length=20), nullable=True),
    sa.Column('y', sa.String(length=20), nullable=True),
    sa.Column('y1', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=50), nullable=True),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('tag'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_tag_tag_name'), 'tag', ['tag_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_table('position')
    # ### end Alembic commands ###
