"""delete tag

Revision ID: c29e2ee7c099
Revises: 25a6378f630b
Create Date: 2022-01-02 16:17:54.176999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c29e2ee7c099'
down_revision = '25a6378f630b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_tag_name', table_name='tag')
    op.drop_index('uuid', table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tag_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uuid', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uuid', 'tag', ['uuid'], unique=False)
    op.create_index('ix_tag_tag_name', 'tag', ['tag_name'], unique=False)
    # ### end Alembic commands ###
