"""add atribute to tag-image

Revision ID: ddd38fefd0e0
Revises: 12eaaf1c8ba2
Create Date: 2022-01-02 16:40:47.733410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddd38fefd0e0'
down_revision = '12eaaf1c8ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagetotag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.String(length=20), nullable=True),
    sa.Column('x1', sa.String(length=20), nullable=True),
    sa.Column('y', sa.String(length=20), nullable=True),
    sa.Column('y1', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id', 'image_id', 'tag_id')
    )
    op.drop_table('image_tag')
    op.drop_table('position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('img_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('x', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('x1', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('y', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('y1', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['image.id'], name='position_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('image_tag',
    sa.Column('image_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name='image_tag_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='image_tag_ibfk_2'),
    sa.PrimaryKeyConstraint('image_id', 'tag_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('imagetotag')
    # ### end Alembic commands ###
